### ISSUE TITLE
无法下载pdf，页面作者也无法点击链接

### ISSUE THREAD

**Issue by ghost** [MkQtS/CNKI-Redirect#1]
您好！感谢您为我们科研人员写的一个脚本，在使用过程中发现一下问题，望采纳！
无法下载pdf，页面作者也无法点击链接。另外建议把登陆界面取消！
再次感谢您

**Comment by MkQtS** [comment]
抱歉没看到 issue ~~（去年毕业，不关心知网了）~~

这个脚本基本不会修改知网页面（仅在给未提供 `PDF 下载` 按钮的无追踪页面添加此按钮），也不会加这种功能，不会影响文件下载/点击链接等，你遇到的问题可能是知网本身的限制或是同时使用的其他脚本造成的。
